### ISSUE TITLE
change 23 on letterman to single digit

### ISSUE THREAD

**Issue by russellgoldenberg** [the-pudding/boybands#100]

**Comment by mlkyusuf** [comment]
Increased the size also and did the same for the jersey so they're clearer at smaller sizes.

<img width="411" alt="screen shot 2018-11-20 at 20 37 03" src="https://user-images.githubusercontent.com/45187487/48813337-6f6f0900-ed04-11e8-890d-f6ae9ac5baf5.png">
<img width="360" alt="screen shot 2018-11-20 at 20 38 47" src="https://user-images.githubusercontent.com/45187487/48813338-6f6f0900-ed04-11e8-8c22-5855fb45b220.png">
