### ISSUE TITLE
Can long braids be longer? 

### ISSUE THREAD

**Issue by ProQuestionAsker** [the-pudding/boybands#102]
Guy with long braids looks like this: 
<img width="239" alt="screen shot 2018-11-20 at 3 00 25 pm" src="https://user-images.githubusercontent.com/11020849/48808261-22c00980-ecd5-11e8-9d6a-c13a2ea11618.png">

but long braids are drawn like this: 
<img width="116" alt="screen shot 2018-11-20 at 3 01 46 pm" src="https://user-images.githubusercontent.com/11020849/48808285-39fef700-ecd5-11e8-8acd-85f5685ec27a.png">

**Comment by mlkyusuf** [comment]
Here's the update. Lemme know if this works.

<img width="450" alt="screen shot 2018-11-20 at 20 32 14" src="https://user-images.githubusercontent.com/45187487/48813124-71849800-ed03-11e8-971f-6c57605e815d.png">
