### ISSUE TITLE
 Odd light yellow lighting on hair

### ISSUE THREAD

**Issue by mlkyusuf** [the-pudding/boybands#114]
There's a weird yellow lighting that appears over the hair of some of the characters.

Here's the ones where I noticed the issue: 

IMx - Marques Houston
IMx - Kelton Kessee
LFO - Richard Burton Cronin
Immature - Jerome "Romeo" Jones
The Click Five - Ben Romans 

<img width="199" alt="screen shot 2018-11-24 at 22 19 12" src="https://user-images.githubusercontent.com/45187487/48975144-92692800-f038-11e8-8608-94a671ae288f.png">

**Comment by russellgoldenberg** [comment]
those are intentional - frosted tips :)

but maybe if you didn't pick it up on it then it won't register with others...

**Comment by mlkyusuf** [comment]
Ah! Yes, you did mention that earlier. Completely forgot.

Looks good now that I realize what they are.
