### ISSUE TITLE
Drums missing drumsticks

### ISSUE THREAD

**Issue by mlkyusuf** [the-pudding/boybands#115]
The drum animations are currently missing the drumstick layers.

Here's the layers:

- .instrument--left-stick-drums
- .instrument--right-stick-drums

Do let me know if they need to be renamed or adjusted in any way.

Example:

Musical Youth - Frederick "Junior" Waite

<img width="185" alt="screen shot 2018-11-24 at 22 17 15" src="https://user-images.githubusercontent.com/45187487/48975190-2935e480-f039-11e8-9f41-f4c9bfee79d6.png">

**Comment by russellgoldenberg** [comment]
ah yes instruments are just the instrument themselves to keep the logic simple. i will just make note to add drumstick layer if drummer.
