### ISSUE TITLE
Wrong head layer for character

### ISSUE THREAD

**Issue by mlkyusuf** [the-pudding/boybands#116]
One character (Jodeci - Kedric "K-Ci" Hailey) appears to have an incorrect head selection. 

It's currently set as .skin--general, but should be .skin--bald. 

His bandmember Joel "JoJo" Hailey has the correct selections.

Not a big issue as it's barely visible.

<img width="131" alt="screen shot 2018-11-24 at 22 18 50" src="https://user-images.githubusercontent.com/45187487/48975240-5f279880-f03a-11e8-886f-7697db4936f7.png">

**Comment by russellgoldenberg** [comment]
ah i think we are giving anyone that is wearing a hat and not on the special hat list the `skin--general`, should we just give them all `skin--bald` instead?

**Comment by russellgoldenberg** [comment]
``
