### ISSUE TITLE
test mobile

### ISSUE THREAD

**Issue by russellgoldenberg** [the-pudding/boybands#120]

**Comment by ProQuestionAsker** [comment]
- [ ] Pudding logo location is off
- [ ] consider adding "Find a band" above mute button
- [ ] Audio only plays with headphones in
- [ ] Audio levels vary widely on mobile (some a good volume while others are really quiet)

**Comment by russellgoldenberg** [comment]
what do you mean dims? sounds like just your personal phone settings

**Comment by ProQuestionAsker** [comment]
Ya, like battery saving mode. But it's because I'm not interacting with the site (and my phone doesn't recognize that it's basically a video that's playing). Not sure that we can fix this though

**Comment by russellgoldenberg** [comment]
re headphones: https://stackoverflow.com/questions/21122418/ios-webaudio-only-works-on-headphones
