### ISSUE TITLE
hair with hats

### ISSUE THREAD

**Issue by russellgoldenberg** [the-pudding/boybands#82]

**Comment by russellgoldenberg** [comment]
- high top (baseballcap, flathat, du rag)
- shaggy (baseballcap)
- curly (bandana)
- braids (beanie)

**Comment by mlkyusuf** [comment]
Just added these. They're also in the crosswalk doc.

baseballcap-hightop-short
baseballcap-hightop-medium
baseballcap-shaggy
flathat-hightop-short
flathat-hightop-medium
dorag-hightop-medium
dorag-hightop-short
bandana-curly-short
bandana-curly-medium

- Shaggy works for all the shaggy variations (short-long)
- The dorags and bandanas look a bit odd given the size of the curly/high top hair styles. Lemme know if you reckon they're alright.
