### ISSUE TITLE
loop for instrument animations

### ISSUE THREAD

**Issue by russellgoldenberg** [the-pudding/boybands#96]

**Comment by mlkyusuf** [comment]
Weird, I do see it on the site like you mentioned, but I just double-checked this again and everything looks alright in the After Effects file.

Could it be that the start and end frames need to be adjusted?

Here they are again:

Tambourine:
Start - 762 
End - 858

Bass: 
Start - 870
End - 966

**Comment by russellgoldenberg** [comment]
Ok I have those - it looks like might be an issue on our end. Regardless, some requests:

- those two animations are much longer than the others, you only need to do a single loop and we should handle repeating on our end. 
- (for all instrument animations) can the loop start/end at the vertical position? Attached image of start positions.
<img width="634" alt="screen shot 2018-11-21 at 9 05 42 am" src="https://user-images.githubusercontent.com/324631/48846286-b8f33e80-ed6c-11e8-844c-5bf532ff2730.png">

**Comment by russellgoldenberg** [comment]
PS we aren't using microphone animation, so you can remove those (and the microphone layer)

**Comment by russellgoldenberg** [comment]
yep!

**Comment by mlkyusuf** [comment]
Awesome, will update it today.
